//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schronisko
{
    using System;
    using System.Collections.Generic;
    
    public partial class pracownik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pracownik()
        {
            this.historia_adopcji = new HashSet<historia_adopcji>();
        }
    
        public int id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string pesel { get; set; }
        public string miasto { get; set; }
        public Nullable<int> kod_pocztowy { get; set; }
        public string ulica { get; set; }
        public string nr_mieszkania { get; set; }
        public int stanowisko_id { get; set; }
        public int Uzytkownik_Info_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historia_adopcji> historia_adopcji { get; set; }
        public virtual stanowisko stanowisko { get; set; }
        public virtual uzytkownik uzytkownik { get; set; }
    }
}
