//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schronisko
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchroniskoBazaEntities : DbContext
    {
        public SchroniskoBazaEntities()
            : base("name=SchroniskoBazaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<historia_adopcji> historia_adopcji { get; set; }
        public virtual DbSet<kojec> kojec { get; set; }
        public virtual DbSet<konto_info> konto_info { get; set; }
        public virtual DbSet<pracownik> pracownik { get; set; }
        public virtual DbSet<rasa> rasa { get; set; }
        public virtual DbSet<stanowisko> stanowisko { get; set; }
        public virtual DbSet<uprawnienia> uprawnienia { get; set; }
        public virtual DbSet<uzytkownik> uzytkownik { get; set; }
        public virtual DbSet<zwierze> zwierze { get; set; }
    }
}
