//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Schronisko
{
    using System;
    using System.Collections.Generic;
    
    public partial class zwierze
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zwierze()
        {
            this.historia_adopcji = new HashSet<historia_adopcji>();
        }
    
        public int id { get; set; }
        public string nazwa { get; set; }
        public Nullable<System.DateTime> data_ur { get; set; }
        public string kastracja { get; set; }
        public int Kojec_id { get; set; }
        public int rasa_id { get; set; }
        public string zdjecie { get; set; }
        public string status { get; set; }
        public string plec { get; set; }
        public string gatunek { get; set; }
        public string wielkosc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<historia_adopcji> historia_adopcji { get; set; }
        public virtual kojec kojec { get; set; }
        public virtual rasa rasa { get; set; }
    }
}
